name:       'CSE 440'

brandimage: ''
brandtext:  'CSE 440 - Introduction to HCI - Winter 2018'

lessc: node_modules/.bin/lessc

navbar:
  items:
    - text: 'Home'
      link: 'index.html'
    - text: 'Projects'
      link: 'projects.html'
    - text: 'Calendar'
      link: 'calendar.html'

exclude:
  # base
  - base.__init__.py
  - base/invoke
  - base/readme
  # Bootstrap source files
  - bootstrap/less
  # CSS/LESS files that are included by other less files and cannot compile on their own
  - css/styles.less
  - css/base/base_styles.less
  - css/base/base_variables.less
  - css/base/syntax.css
  - css/base/bar/base_bar.less
  - css/base/freelancer/base_freelancer.less
  - css/base/freelancer/freelancer.less
  - css/base/freelancer/mixins.less
  - css/base/freelancer/variables.less
  # LESS files in a project, due to copying in CSS libraries
  - projects/*.less
  # Node
  - node_modules
  - npm-shrinkwrap.json
  - package.json
  # Python
  - env35
  - requirements3.in
  - requirements3.txt
  - tasks.py
  - tasks.pyc
  # README
  - README.md
  # Ruby
  - Gemfile
  - Gemfile.lock
  # Secrets
  - secrets
  # Tests
  - tests

collections:
  assignments:
    output: true
  projects:
    output: true
